### model
# model_name_or_path: ../pretrained_models/Meta-Llama-3.1-8B-Instruct
# model_name_or_path: ../pretrained_models/DeepSeek-R1-Distill-Llama-8B
model_name_or_path: ../pretrained_models/Qwen/Qwen3-1.7B
### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
lora_rank: 32
lora_alpha: 64
lora_dropout: 0.05
seed: 42

### dataset
dataset: pdtb2_train_qwen3_max_exp
template: qwen3
cutoff_len: 2048
# max_samples: 25
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: expt/rl_cold_start/pdtb2/qwen3-1.7b-exp_by_qwen3/epo1
logging_steps: 0.01
save_steps: 0.5
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 1
learning_rate: 5.0e-5
num_train_epochs: 1
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
use_rslora: true
# fp16: true
ddp_timeout: 180000000
report_to: tensorboard

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500